script:
  - mkdir dist
  - cp index.html dist/
  - cp OpenAPI.yaml dist/
deploy:
  - provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    local-dir: dist
    on:
      branch: master
branches:
  only:
    - master