---
swagger: '2.0'
info:
  title: VyatSU schedule backend
  contact:
    name: Ali Rzaev
    email: alirzaev1996@gmail.com
    url: https://vk.me/rzaevali
  version: 2.1.0
host: vyatsu-schedule-api.herokuapp.com 
paths:
  "/api/v2/calls":
    get:
      summary: Call schedule
      produces:
      - application/json
      responses:
        '200':
          description: |
            List of pairs represent the time of the beginning and the end of lesson.
          schema:
            type: array
            items:
              "$ref": "#/definitions/Call"
          examples:
            application/json:
            - start: '8:20'
              end: '9:50'
            - start: '10:00'
              end: '11:30'
            - start: '11:45'
              end: '13:15'
            - start: '14:00'
              end: '15:30'
            - start: '15:45'
              end: '17:15'
            - start: '17:20'
              end: '18:50'
            - start: '18:55'
              end: '20:25'
        '500':
          description: Unexpected error
          schema:
            "$ref": "#/definitions/UnknownError"
          examples:
            application/json:
              error: INTERNAL SERVER ERROR
  "/api/v2/groups/list":
    get:
      summary: List of groups
      produces:
      - application/json
      responses:
        '200':
          description: List of objects represents group information
          schema:
            type: array
            items:
              "$ref": "#/definitions/Group"
          examples:
            application/json:
            - id: '8472'
              name: ПИм-2302-02-00
            - id: '8949'
              name: МКм-1301-51-00
            - id: '8305'
              name: МКб-3301-51-00
            - id: '8423'
              name: ПМИм-2301-01-00
        '500':
          description: Unexpected error
          schema:
            "$ref": "#/definitions/UnknownError"
          examples:
            application/json:
              error: INTERNAL SERVER ERROR
  "/api/v2/groups/by_faculty":
    get:
      summary: Lists of groups by faculties
      produces:
      - application/json
      responses:
        '200':
          description: Lists of groups grouped by faculty
          schema:
            type: array
            items:
              "$ref": "#/definitions/Faculty"
          examples:
            application/json:
            - faculty: ИББТ (Институт биологии и биотехнологии)
              groups:
              - id: '8853'
                name: БТб-1101-02-00
              - id: '8854'
                name: БТб-1102-02-00
            - faculty: ФАВТ (Факультет автоматики и вычислительной техники)
              groups:
              - id: '8850'
                name: БИб-1301-01-00
              - id: '8367'
                name: БИб-2301-01-00
        '500':
          description: Unexpected error
          schema:
            "$ref": "#/definitions/UnknownError"
          examples:
            application/json:
              error: INTERNAL SERVER ERROR
  "/api/v2/schedule/{group_id}/{season}":
    get:
      summary: Schedule of group
      produces:
      - application/json
      parameters:
      - name: group_id
        in: path
        type: string
        description: Group you want the schedule for
      - name: season
        in: path
        type: string
        description: Semester (aka __season__) you want the group schedule for
        enum:
        - autumn
        - spring
      responses:
        '200':
          description: The two-week schedule of group
          schema:
            "$ref": "#/definitions/Schedule"
          examples:
            application/json:
              weeks:
              - - - ''
                  - Математика Чтение лекций Ситникова И.В. 1-242
                  - Физика Проведение практических занятий, семинаров Фролов В.М.
                    1-222
                  - ''
                  - ''
                  - ''
                  - ''
                - - Общая физическая подготовка Проведение практических занятий, семинаров
                    Преподаватель К.Ф. 9-122
                  - Общая физическая подготовка Проведение практических занятий, семинаров
                    Преподаватель К.Ф. 9-122
                  - Теория автоматов Проведение практических занятий, семинаров Мельцов
                    В.Ю. 1-239
                  - ИВТб-2301-01-00, 01 подгруппа Лб. Электротехника и электроника
                    Куваев А.С. 2-308
                  - ИВТб-2301-01-00, 01 подгруппа Лб. Электротехника и электроника
                    Куваев А.С. 2-308
                  - ''
                  - ''
                - - ИВТб-2301-01-00, 01 подгруппа Физика Проведение лабораторных занятий
                    в подгруппах Фролов В.М. 14-330 ИВТб-2301-01-00, 02 подгруппа
                    Физика Проведение лабораторных занятий в подгруппах Заграй И.А.
                    14-240
                  - ИВТб-2301-01-00, 01 подгруппа Физика Проведение лабораторных занятий
                    в подгруппах Фролов В.М. 14-330 ИВТб-2301-01-00, 02 подгруппа
                    Физика Проведение лабораторных занятий в подгруппах Заграй И.А.
                    14-240
                  - ''
                  - ИВТб-2301-01-00, 02 подгруппа Лб. Электротехника и электроника
                    Куваев А.С. 2-308
                  - ИВТб-2301-01-00, 02 подгруппа Лб. Электротехника и электроника
                    Куваев А.С. 2-308
                  - ''
                  - ''
                - - ИВТб-2301-01-00, 02 подгруппа Лб. Вычислительная математика Старостин
                    П.А. 1-114
                  - ИВТб-2301-01-00, 02 подгруппа Лб. Вычислительная математика Старостин
                    П.А. 1-114
                  - Вычислительная математика Проведение практических занятий, семинаров
                    Старостин П.А. 1-313
                  - Вычислительная математика Чтение лекций Исупов К.С. 1-313
                  - ''
                  - ''
                  - ''
                - - ''
                  - Теория автоматов Чтение лекций Мельцов В.Ю. 1-242
                  - Электротехника и электроника Чтение лекций Куваев А.С. 1-242
                  - ''
                  - ''
                  - ''
                  - ''
                - - ИВТб-2301-01-00, 02 подгруппа Лб. Компьютерная графика Вожегов
                    Д.В. 1-113
                  - ИВТб-2301-01-00, 02 подгруппа Лб. Компьютерная графика Вожегов
                    Д.В. 1-113
                  - Компьютерная графика Чтение лекций Вожегов Д.В. 1-313
                  - ''
                  - ''
                  - ''
                  - ''
              - - - ''
                  - Математика Чтение лекций Ситникова И.В. 1-242
                  - Физика Чтение лекций Фролов В.М. 1-242
                  - ИВТб-2301-01-00, 02 подгруппа Лб. Электротехника и электроника
                    Куваев А.С. 2-308
                  - ИВТб-2301-01-00, 01 подгруппа Лб. Электротехника и электроника
                    Куваев А.С. 2-308
                  - ''
                  - ''
                - - Физическая культура Проведение практических занятий, семинаров
                    Преподаватель К.Ф. 9-122_
                  - Физическая культура Проведение практических занятий, семинаров
                    Преподаватель К.Ф. 9-122_
                  - Иностранный язык Проведение практических занятий, семинаров Дубовцева
                    Л.В. 2-102
                  - ''
                  - ''
                  - ''
                  - ''
                - - ИВТб-2301-01-00, 01 подгруппа Лб. Теория автоматов Мельцов В.Ю.
                    1-239 ИВТб-2301-01-00, 02 подгруппа Лб. Теория автоматов Мельцов
                    В.Ю. 1-239
                  - ИВТб-2301-01-00, 01 подгруппа Лб. Теория автоматов Мельцов В.Ю.
                    1-239 ИВТб-2301-01-00, 02 подгруппа Лб. Теория автоматов Мельцов
                    В.Ю. 1-239
                  - Теория автоматов Чтение лекций Мельцов В.Ю. 1-128
                  - Компьютерная графика Чтение лекций Вожегов Д.В. 1-128
                  - ''
                  - ''
                  - ''
                - - ИВТб-2301-01-00, 01 подгруппа Математика Проведение лабораторных
                    занятий в подгруппах Серова А.С. 2-207
                  - ИВТб-2301-01-00, 01 подгруппа Математика Проведение лабораторных
                    занятий в подгруппах Серова А.С. 2-207
                  - Электротехника и электроника Чтение лекций Куваев А.С. 1-242
                  - Вычислительная математика Чтение лекций Исупов К.С. 1-242
                  - ''
                  - ''
                  - ''
                - - ИВТб-2301-01-00, 01 подгруппа Лб. Вычислительная математика Старостин
                    П.А. 1-113
                  - ИВТб-2301-01-00, 01 подгруппа Лб. Вычислительная математика Старостин
                    П.А. 1-113
                  - ''
                  - ''
                  - ''
                  - ''
                  - ''
                - - ИВТб-2301-01-00, 01 подгруппа Лб. Компьютерная графика Вожегов
                    Д.В. 1-113
                  - ИВТб-2301-01-00, 01 подгруппа Лб. Компьютерная графика Вожегов
                    Д.В. 1-113
                  - ИВТб-2301-01-00, 02 подгруппа Математика Проведение лабораторных
                    занятий в подгруппах Серова А.С. 2-207
                  - ИВТб-2301-01-00, 02 подгруппа Математика Проведение лабораторных
                    занятий в подгруппах Серова А.С. 2-207
                  - ''
                  - ''
                  - ''
              group: ИВТб-2301-01-00
              today:
                week: 1
                dayOfWeek: 0
                date: '25122017'
              date_range:
                begin: '18122017'
                end: '31122017'
        '422':
          description: Error during schedule parsing or due to incorrect path params
          schema:
            "$ref": "#/definitions/ScheduleError"
          examples:
            application/json:
              error: NO_SUCH_GROUP
        '500':
          description: Unexpected error
          schema:
            "$ref": "#/definitions/UnknownError"
          examples:
            application/json:
              error: INTERNAL SERVER ERROR
  "/api/v2/season/current":
    get:
      summary: Current season
      produces:
      - application/json
      responses:
        '200':
          description: Current season
          schema:
            "$ref": "#/definitions/Season"
          examples:
            application/json:
              season: spring
        '500':
          description: Unexpected error
          schema:
            "$ref": "#/definitions/UnknownError"
          examples:
            application/json:
              error: INTERNAL SERVER ERROR
definitions:
  Call:
    type: object
    properties:
      start:
        type: string
        description: Beginning of lesson in the time format `hh:mm`
      end:
        type: string
        description: End of lesson in the time format `hh:mm`
  Group:
    type: object
    properties:
      id:
        type: string
        description: Group ID
      name:
        type: string
        description: Group name
  Faculty:
    type: object
    properties:
      faculty:
        type: string
        description: Faculty shorthand name with full name in parentheses 
      groups:
        type: array
        description: List of groups in the faculty
        items:
          "$ref": "#/definitions/Group"
  Day:
    type: array
    items:
      type: string
  Week:
    type: array
    items:
      "$ref": "#/definitions/Day"
  DateRange:
    type: object
    description: Date range the schedule is valid for
    properties:
      begin:
        type: string
        description: Beginning of the range in the date format `ddMMyyyy`
      end:
        type: string
        description: End of the range in the date format `ddMMyyyy`
  Today:
    type: object
    description: Pointer to the today schedule in the field `weeks`
    properties:
      week:
        type: integer
        description: Index of the week
        minimum: 0
        maximum: 1
      dayOfWeek:
        type: integer
        description: Index of the day in the week
        minimum: 0
        maximum: 5
      date:
        type: string
        description: Today's date in the format `ddMMyyyy`
  Schedule:
    type: object
    properties:
      group:
        type: string
        description: Group name
      today:
        "$ref": "#/definitions/Today"
      date_range:
        "$ref": "#/definitions/DateRange"
      weeks:
        type: array
        description: |
          Schedule as three-dimensional array `[week_number][day_number][lesson_number]` of strings, where 
          * week_number = `0..1`, `0` - odd week, `1` - even week
          * day_number = `0..5`, `0` - Monday, `1` - Tuesday, etc
          * lesson_number = `0..6`, `0` - 1st lesson, `1` - 2nd lesson, etc
        items:
          "$ref": "#/definitions/Week"
  ScheduleError:
    type: object
    properties:
      error:
        description: |
          Error description. Known error types:
          * PDF_PARSE_ERROR - Some error was occurred during schedule parsing
          * INVALID_SEASON - Parameter `season` doesn't equal to `autumn` nor `spring`
          * NO_SUCH_GROUP - No group with group ID passed in parameter `group_id`
          * NO_SUCH_SCHEDULE - No schedule for given combination of group ID and season
        type: string
        maxLength: 40
  UnknownError:
    type: object
    properties:
      error:
        description: Error description
        type: string
        maxLength: 40
  Season:
    type: object
    properties:
      season:
        type: string
        description: 'Name of the season: `autumn` - first, `spring` - second'
        enum:
        - autumn
        - spring
